---
spring:
  config.activate.on-profile: default
  datasource:
#    url: "jdbc:sqlite:file::memory:?cache=shared"
    url: "jdbc:sqlite:/Users/user/src/github.com/knsugiyama/study-sap-cap-cloud/myapp/sqlite.db"
    driver-class-name: org.sqlite.JDBC
#    initialization-mode: always
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
